title: "@nathancorvussolis"
description: 
google_analytics: 
show_downloads: false
twitter:
  username: corvussolis
  card: summary
social:
  name: nathancorvussolis
  links:
    - https://twitter.com/corvussolis
    - https://github.com/nathancorvussolis
logo: /logo.png
author:
  twitter: corvussolis
image:
  path: /logo.png
  height: 600
  width: 600
defaults:
  - scope:
      path: ""
    values:
      image: /logo.png
theme: jekyll-theme-slate
gems:
  - jekyll-mentions
